package com.bbs.app.entity;

public class ContentsKey {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.bbs_id
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    private Integer bbsId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column contents.no
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    private Integer no;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.bbs_id
     *
     * @return the value of contents.bbs_id
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    public Integer getBbsId() {
        return bbsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.bbs_id
     *
     * @param bbsId the value for contents.bbs_id
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    public void setBbsId(Integer bbsId) {
        this.bbsId = bbsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column contents.no
     *
     * @return the value of contents.no
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    public Integer getNo() {
        return no;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column contents.no
     *
     * @param no the value for contents.no
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    public void setNo(Integer no) {
        this.no = no;
    }
}