package com.bbs.app.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class ContentsExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contents
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contents
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table contents
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    public ContentsExample() {
        oredCriteria = new ArrayList<>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table contents
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andBbsIdIsNull() {
            addCriterion("bbs_id is null");
            return (Criteria) this;
        }

        public Criteria andBbsIdIsNotNull() {
            addCriterion("bbs_id is not null");
            return (Criteria) this;
        }

        public Criteria andBbsIdEqualTo(Integer value) {
            addCriterion("bbs_id =", value, "bbsId");
            return (Criteria) this;
        }

        public Criteria andBbsIdNotEqualTo(Integer value) {
            addCriterion("bbs_id <>", value, "bbsId");
            return (Criteria) this;
        }

        public Criteria andBbsIdGreaterThan(Integer value) {
            addCriterion("bbs_id >", value, "bbsId");
            return (Criteria) this;
        }

        public Criteria andBbsIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("bbs_id >=", value, "bbsId");
            return (Criteria) this;
        }

        public Criteria andBbsIdLessThan(Integer value) {
            addCriterion("bbs_id <", value, "bbsId");
            return (Criteria) this;
        }

        public Criteria andBbsIdLessThanOrEqualTo(Integer value) {
            addCriterion("bbs_id <=", value, "bbsId");
            return (Criteria) this;
        }

        public Criteria andBbsIdIn(List<Integer> values) {
            addCriterion("bbs_id in", values, "bbsId");
            return (Criteria) this;
        }

        public Criteria andBbsIdNotIn(List<Integer> values) {
            addCriterion("bbs_id not in", values, "bbsId");
            return (Criteria) this;
        }

        public Criteria andBbsIdBetween(Integer value1, Integer value2) {
            addCriterion("bbs_id between", value1, value2, "bbsId");
            return (Criteria) this;
        }

        public Criteria andBbsIdNotBetween(Integer value1, Integer value2) {
            addCriterion("bbs_id not between", value1, value2, "bbsId");
            return (Criteria) this;
        }

        public Criteria andNoIsNull() {
            addCriterion("no is null");
            return (Criteria) this;
        }

        public Criteria andNoIsNotNull() {
            addCriterion("no is not null");
            return (Criteria) this;
        }

        public Criteria andNoEqualTo(Integer value) {
            addCriterion("no =", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotEqualTo(Integer value) {
            addCriterion("no <>", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoGreaterThan(Integer value) {
            addCriterion("no >", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoGreaterThanOrEqualTo(Integer value) {
            addCriterion("no >=", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoLessThan(Integer value) {
            addCriterion("no <", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoLessThanOrEqualTo(Integer value) {
            addCriterion("no <=", value, "no");
            return (Criteria) this;
        }

        public Criteria andNoIn(List<Integer> values) {
            addCriterion("no in", values, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotIn(List<Integer> values) {
            addCriterion("no not in", values, "no");
            return (Criteria) this;
        }

        public Criteria andNoBetween(Integer value1, Integer value2) {
            addCriterion("no between", value1, value2, "no");
            return (Criteria) this;
        }

        public Criteria andNoNotBetween(Integer value1, Integer value2) {
            addCriterion("no not between", value1, value2, "no");
            return (Criteria) this;
        }

        public Criteria andContributorIsNull() {
            addCriterion("contributor is null");
            return (Criteria) this;
        }

        public Criteria andContributorIsNotNull() {
            addCriterion("contributor is not null");
            return (Criteria) this;
        }

        public Criteria andContributorEqualTo(String value) {
            addCriterion("contributor =", value, "contributor");
            return (Criteria) this;
        }

        public Criteria andContributorNotEqualTo(String value) {
            addCriterion("contributor <>", value, "contributor");
            return (Criteria) this;
        }

        public Criteria andContributorGreaterThan(String value) {
            addCriterion("contributor >", value, "contributor");
            return (Criteria) this;
        }

        public Criteria andContributorGreaterThanOrEqualTo(String value) {
            addCriterion("contributor >=", value, "contributor");
            return (Criteria) this;
        }

        public Criteria andContributorLessThan(String value) {
            addCriterion("contributor <", value, "contributor");
            return (Criteria) this;
        }

        public Criteria andContributorLessThanOrEqualTo(String value) {
            addCriterion("contributor <=", value, "contributor");
            return (Criteria) this;
        }

        public Criteria andContributorLike(String value) {
            addCriterion("contributor like", value, "contributor");
            return (Criteria) this;
        }

        public Criteria andContributorNotLike(String value) {
            addCriterion("contributor not like", value, "contributor");
            return (Criteria) this;
        }

        public Criteria andContributorIn(List<String> values) {
            addCriterion("contributor in", values, "contributor");
            return (Criteria) this;
        }

        public Criteria andContributorNotIn(List<String> values) {
            addCriterion("contributor not in", values, "contributor");
            return (Criteria) this;
        }

        public Criteria andContributorBetween(String value1, String value2) {
            addCriterion("contributor between", value1, value2, "contributor");
            return (Criteria) this;
        }

        public Criteria andContributorNotBetween(String value1, String value2) {
            addCriterion("contributor not between", value1, value2, "contributor");
            return (Criteria) this;
        }

        public Criteria andDateIsNull() {
            addCriterion("date is null");
            return (Criteria) this;
        }

        public Criteria andDateIsNotNull() {
            addCriterion("date is not null");
            return (Criteria) this;
        }

        public Criteria andDateEqualTo(Date value) {
            addCriterion("date =", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotEqualTo(Date value) {
            addCriterion("date <>", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThan(Date value) {
            addCriterion("date >", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateGreaterThanOrEqualTo(Date value) {
            addCriterion("date >=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThan(Date value) {
            addCriterion("date <", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateLessThanOrEqualTo(Date value) {
            addCriterion("date <=", value, "date");
            return (Criteria) this;
        }

        public Criteria andDateIn(List<Date> values) {
            addCriterion("date in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotIn(List<Date> values) {
            addCriterion("date not in", values, "date");
            return (Criteria) this;
        }

        public Criteria andDateBetween(Date value1, Date value2) {
            addCriterion("date between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andDateNotBetween(Date value1, Date value2) {
            addCriterion("date not between", value1, value2, "date");
            return (Criteria) this;
        }

        public Criteria andTextIsNull() {
            addCriterion("text is null");
            return (Criteria) this;
        }

        public Criteria andTextIsNotNull() {
            addCriterion("text is not null");
            return (Criteria) this;
        }

        public Criteria andTextEqualTo(String value) {
            addCriterion("text =", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextNotEqualTo(String value) {
            addCriterion("text <>", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextGreaterThan(String value) {
            addCriterion("text >", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextGreaterThanOrEqualTo(String value) {
            addCriterion("text >=", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextLessThan(String value) {
            addCriterion("text <", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextLessThanOrEqualTo(String value) {
            addCriterion("text <=", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextLike(String value) {
            addCriterion("text like", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextNotLike(String value) {
            addCriterion("text not like", value, "text");
            return (Criteria) this;
        }

        public Criteria andTextIn(List<String> values) {
            addCriterion("text in", values, "text");
            return (Criteria) this;
        }

        public Criteria andTextNotIn(List<String> values) {
            addCriterion("text not in", values, "text");
            return (Criteria) this;
        }

        public Criteria andTextBetween(String value1, String value2) {
            addCriterion("text between", value1, value2, "text");
            return (Criteria) this;
        }

        public Criteria andTextNotBetween(String value1, String value2) {
            addCriterion("text not between", value1, value2, "text");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table contents
     *
     * @mbg.generated do_not_delete_during_merge Mon Aug 31 21:23:56 JST 2020
     */
    public static class Criteria extends GeneratedCriteria {
        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table contents
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}