package com.bbs.app.mapper;

import com.bbs.app.entity.Contents;
import com.bbs.app.entity.ContentsExample;
import com.bbs.app.entity.ContentsKey;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ContentsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    long countByExample(ContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    int deleteByExample(ContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    int deleteByPrimaryKey(ContentsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    int insert(Contents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    int insertSelective(Contents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    List<Contents> selectByExample(ContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    Contents selectByPrimaryKey(ContentsKey key);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    int updateByExampleSelective(@Param("record") Contents record, @Param("example") ContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    int updateByExample(@Param("record") Contents record, @Param("example") ContentsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    int updateByPrimaryKeySelective(Contents record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table contents
     *
     * @mbg.generated Mon Aug 31 21:23:56 JST 2020
     */
    int updateByPrimaryKey(Contents record);
}